language: node_js
node_js:
- '0.10'
script: gulp build
deploy:
  provider: divshot
  api_key:
    secure: RIXC3U7+E8ieDbZ9ZIIoR7UioahCVq/1wJfwZDSlyEIBxNeZcfAZ+cx4OVXpIy7jq1SF8h09HLkScsPIXqP8JBE340UPeAxTtifDwNxj3PlQ0XaQR+szaf4hlGJX2pjEW1+Oui3Ds0gq+g6raKpcflUhdiKpQzuavoArJL/ZLQ0=
  skip_cleanup: true
  on:
    repo: MindKitchen/headcooked.com
